version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # Remova os volumes temporariamente para testar
    # volumes:
    #   - ../frontend:/app
    #   - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000/api
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=docker
    stdin_open: true  
    tty: true         
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=taskmanager
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRE=30d
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
networks:
  task-manager-network:
    driver: bridge
