version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend-app
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskmanager
      JWT_SECRET: your_jwt_secret_key
      JWT_EXPIRE: 30d
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - task-manager-network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend:5000/api
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true  
    tty: true         
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - task-manager-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  task-manager-network:
    driver: bridge